services:
  - type: web
    name: ohitsmetables
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn run:app"
    envVars:
      - key: GOOGLE_CREDS
        value: credentials.json
    plan: free
